Models/Empresa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TP_PWEB.Models
{
    public class Empresa
    {
        [Key]
        public int IdEmpresa { get; set; }

        [Display(Name = "Nome Empresa")]
        [Column("Nome")]
        [Index(IsUnique = true)]
        [StringLength(50)]
        public string NomeEmpresa { get; set; }

        public string ApplicationUserId { get; set; }

        [ForeignKey("ApplicationUserId")]
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}

Models/EstatisticasViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TP_PWEB.Models
{
	public class TopVendaViewModel
	{
		[Display(Name = "Produto")]
		public string NomeProduto { get; set; }
		[Display(Name = "Unidades Vendidas")]
		public int UnidadesVendidas { get; set; }
		[Display(Name = "Faturado")]
		public decimal TotalVendas { get; set; }

		[Display(Name = "Participação nos Rendimentos (%)")]
		[DisplayFormat(DataFormatString = "{0:P1}")]
		public double PercentagemFaturacao { get; set; }
	}

	public class EstatisticasViewModel
	{
		[Display(Name ="Nº de Vendas")]
		public int nVendas { get; set; }

		[Display(Name = "Rendimento Bruto")]
		public decimal totalVendas { get; set; }

		[Display(Name = "Clientes Ativos")]
		public int nClientes { get; set; }

		[Display(Name = "Ano")]
		public string Ano { get; set; }

		[Display(Name = "Mês")]
		public int? Mes { get; set; }

		[Display(Name = "Histórico de Vendas")]
		public List<LinhaCompra> Vendas { get; set; }

		[Display(Name = "Produtos mais vendidos")]
		public List<TopVendaViewModel> TopVendas { get; set; }
	}
}

Controllers/EmpresasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TP_PWEB.Models;
using Microsoft.AspNet.Identity;
using System.Globalization;

namespace TP_PWEB.Controllers
{

    public class EmpresasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Empresas
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var empresas = db.Empresas.Include(e => e.ApplicationUser);
            return View(empresas.ToList());
        }

        // GET: Empresas/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empresa empresa = db.Empresas.Find(id);
            if (empresa == null)
            {
                return HttpNotFound();
            }
            return View(empresa);
        }


        // GET: Empresas/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empresa empresa = db.Empresas.Find(id);
            if (empresa == null)
            {
                return HttpNotFound();
            }

            return View(empresa);
        }

        // POST: Empresas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "IdEmpresa,ApplicationUserId,NomeEmpresa")] Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empresa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(empresa);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize(Roles = "Empresa")]
        public ActionResult Estatisticas(int? mes, string ano)
        {
            var userId = User.Identity.GetUserId();
            var empresa = db.Empresas.Where(e => e.ApplicationUserId == userId).FirstOrDefault();

            if (empresa != null)
			{
                var comprasPesquisadas = db.LinhaCompras.Where(lc => lc.Produto.IdEmpresa == empresa.IdEmpresa);
                var topVendasQuery = db.LinhaCompras.Where(lc => lc.Produto.IdEmpresa == empresa.IdEmpresa);

                if (mes != null)
				{
                    comprasPesquisadas = comprasPesquisadas.Where(c => c.DataConfirmada.Value.Month == mes);
                }

                if (ano != null)
				{
                    if (ano.Length > 0)
					{
                        var anoAsInt = int.Parse(ano);
                        comprasPesquisadas = comprasPesquisadas.Where(c => c.DataConfirmada.Value.Year == anoAsInt);
					}
				}

                decimal totalVendas = 0;
                if (comprasPesquisadas.Count() > 0)
                {
                    totalVendas = comprasPesquisadas.Sum(c => c.Subtotal);
                }

                List<TopVendaViewModel> Top5Vendas = comprasPesquisadas
                    .GroupBy(p => p.Produto)
                    .Select(x => new TopVendaViewModel
                    {
                        NomeProduto = x.Key.Nome,
                        UnidadesVendidas = x.Sum(y => y.Unidades),
                        TotalVendas = x.Sum(y => y.Unidades) * x.Key.Preco,
                        PercentagemFaturacao = (double)(x.Sum(y => y.Unidades) * x.Key.Preco / totalVendas)
                    })
                    .OrderByDescending(x => x.UnidadesVendidas)
                    .Take(5)
                    .ToList();

         
         
                List<SelectListItem> listaMeses = new SelectList(
                    Enumerable.Range(1, 12).Select(i => new { val = i, txt = DateTimeFormatInfo.CurrentInfo.GetMonthName(i) }),
                    "val",
                    "txt"
                ).ToList();

                listaMeses.Insert(0, new SelectListItem
                {
                    Text = "- Selecionar -",
                    Value = null,
                    Selected = true
                });

                ViewBag.Mes = new SelectList(listaMeses, "Value", "Text");
                return View(new EstatisticasViewModel {
                    nVendas = comprasPesquisadas.Count(),
                    totalVendas = totalVendas,
                    nClientes = comprasPesquisadas.Select(c => c.Compra.ApplicationUserId).Distinct().Count(),
                    Vendas = comprasPesquisadas.Include(p => p.Produto).ToList(),
                    TopVendas = Top5Vendas,
                    Ano = ano,
                    Mes = mes
                });
			}

            return View();
        }
    }
}

Views/Empresas/Details.cshtml
@model TP_PWEB.Models.Empresa

@{
    ViewBag.Title = "Detalhes";
}

<br />
<h5>Detalhes Empresa</h5>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeEmpresa)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NomeEmpresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Email)
        </dd>

        <dt>
            Nome proprietário
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.NomeCompleto)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdEmpresa }, new { @class = "btn btn-warning" }) &nbsp;
    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
</p>

Views/Empresas/Edit.cshtml
@model TP_PWEB.Models.Empresa

@{
    ViewBag.Title = "Edit";
}
<br />
<h5>Editar Empresa</h5>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdEmpresa)

    <div class="form-group">
        @Html.LabelFor(model => model.NomeEmpresa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NomeEmpresa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NomeEmpresa, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.ApplicationUserId)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Empresas/Estatisticas.cshtml
@model TP_PWEB.Models.EstatisticasViewModel
@{
    ViewBag.Title = "Estatisticas";
}
<br />
<br />
@using (Html.BeginForm("Estatisticas", "Empresas", FormMethod.Get))
{
    <div class="form-group row">
            @Html.LabelFor(model => model.Mes, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-sm-10">
            @Html.DropDownList("Mes", null, htmlAttributes: new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-sm-10">
            @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <input type="submit" value="Pesquisar" class="btn btn-primary" />
        </div>
    </div>
    @*<div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Mes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Mes", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Pesquisar" class="btn btn-primary" />
        </div>
    </div>*@
}
<h4>
    Relatório Sumariado
</h4>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nVendas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.totalVendas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nClientes)
        </th>
    </tr>
    <tr>
        <td>
            @Html.DisplayFor(model => model.nVendas)
        </td>
        <td>
            @Html.DisplayFor(model => model.totalVendas)
        </td>
        <td>
            @Html.DisplayFor(model => model.nClientes)
        </td>
    </tr>
</table>
<h4>
    @Html.DisplayNameFor(model => model.TopVendas)
</h4>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(_ => Model.TopVendas[0].NomeProduto)
        </th>
        <th>
            @Html.DisplayNameFor(_ => Model.TopVendas[0].UnidadesVendidas)
        </th>
        <th>
            @Html.DisplayNameFor(_ => Model.TopVendas[0].TotalVendas)
        </th>
        <th>
            @Html.DisplayNameFor(_ => Model.TopVendas[0].PercentagemFaturacao)
        </th>
    </tr>
    @foreach (var item in Model.TopVendas)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomeProduto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnidadesVendidas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalVendas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PercentagemFaturacao)
            </td>
        </tr>
    }
</table>
<h4>
    @Html.DisplayNameFor(model => model.Vendas)
</h4>
<table class="table">
    <tr>
        <th>
            Produto
        </th>
        <th>
            Preço
        </th>
        <th>
            Unidades
        </th>
        <th>
            DataConfirmada
        </th>
        <th>
            Subtotal
        </th>
    </tr>
    @if (Model.Vendas.Count() == 0)
    {
        <tr>
            <td colspan="5">
                Não existem registos correspondentes aos critérios
            </td>
        </tr>
    }
    @foreach (var item in Model.Vendas)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Produto.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Produto.Preco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Unidades)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataConfirmada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subtotal)
            </td>
        </tr>
    }

</table>

Views/Empresas/Index.cshtml
@model IEnumerable<TP_PWEB.Models.Empresa>

@{
    ViewBag.Title = "Lista de Empresas";
}

<br />
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NomeEmpresa)
            
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationUser.Email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NomeEmpresa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationUser.Email)
            
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id = item.IdEmpresa }, new { @class = "btn btn-warning" }) &nbsp;
            @Html.ActionLink("Detalhes", "Details", new { id = item.IdEmpresa }, new { @class = "btn btn-info" })
        </td>
    </tr>
}

</table>