Controllers/ProdutoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TP_PWEB.Models;

using Microsoft.AspNet.Identity;

namespace TP_PWEB.Controllers
{
    public class ProdutoesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Produtoes
        public ActionResult Index(string produto, int? IdCategoria)
        {
            List<ProdutoViewModel> prods = new List<ProdutoViewModel>();
            var userId = User.Identity.GetUserId();
            List<Produto> produtos = new List<Produto>();

            if (User.IsInRole("Empresa"))
            {
                var empresa = db.Empresas.FirstOrDefault(e => e.ApplicationUserId == userId);
                if (empresa == null)
                {
                    return View(prods);
                }

                produtos = db.Produtos.Where(p => p.IdEmpresa == empresa.IdEmpresa).OrderBy(p => p.Categoria.NomeCategoria).ThenBy(p => p.Nome).ToList();
            }
            else if (User.IsInRole("Funcionario"))
            {
                var funcionario = db.Funcionarios.FirstOrDefault(f => f.ApplicationUserId == userId);
                if (funcionario == null)
                {
                    return View(prods);
                }

                produtos = db.Produtos.Where(p => p.IdEmpresa == funcionario.IdEmpresa).OrderBy(p => p.Categoria.NomeCategoria).ThenBy(p => p.Nome).ToList();
            }
            else if (User.IsInRole("Cliente"))
			{
                IQueryable<Produto> produtosPesquisados = db.Produtos;

                if (produto != null)
				{
                    produtosPesquisados = produtosPesquisados.Where(p => p.Nome.Contains(produto));
                    
				}

                if (IdCategoria != null)
				{
                    produtosPesquisados = produtosPesquisados.Where(p => p.Categoria.IdCategoria == IdCategoria);
				}

				SelectList categorias = new SelectList(db.Categorias, "IdCategoria", "NomeCategoria");
				List<SelectListItem> listaCategorais = categorias.ToList();
				listaCategorais.Insert(0, new SelectListItem
				{
					Text = "- Selecionar -",
					Value = null,
					Selected = true
				});

                ViewBag.Produto = produto;
                ViewBag.IdCategoria = new SelectList(listaCategorais, "Value", "Text");

                produtos = produtosPesquisados.Where(p => p.Apagado == false).OrderBy(p => p.Categoria.NomeCategoria).ThenBy(p => p.Nome).ToList();
            }
            else
            {
                produtos = db.Produtos.OrderBy(p => p.Categoria.NomeCategoria).ThenBy(p => p.Nome).ToList();
            }

            produtos.ForEach(x => {
                var prodviewmodel = new ProdutoViewModel
                {
                    NomeProduto = x.Nome,
                    IdProduto = x.IdProduto,
                    Categoria = x.Categoria.NomeCategoria,
                    Vendedor = x.Empresa.NomeEmpresa,
                    EmStock = x.EmStock,
                    Unidades = x.UnidadesEmStock,
                    Preco = x.Preco,
                    Apagado = x.Apagado
                };

                var promocao = db.Promocoes.Where(p => p.IdProduto == x.IdProduto && p.Ativa == true).FirstOrDefault();
                if (promocao != null)
                {
                    prodviewmodel.IdPromocao = promocao.IdPromocao;
                    prodviewmodel.PrecoPromocional = promocao.PrecoNovo;
                    prodviewmodel.Desconto = promocao.Percentagem;
                }

                prods.Add(prodviewmodel);
            });

            return View(prods);
        }

        public ActionResult CriarPromocao(int? id)
		{
            if (id == null)
			{
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Produto produto = db.Produtos.Find(id);
            if (produto == null)
			{
                return RedirectToAction("Index");
			}

            ViewBag.Produto = produto;
            return View();
		}

        [Authorize(Roles = "Funcionario")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CriarPromocao([Bind(Include = "IdPromocao,IdProduto,Percentagem")] Promocao promocao)
		{
            if (ModelState.IsValid)
            {
                var produto = db.Produtos.Find(promocao.IdProduto);
                if (produto == null)
				{
                    ModelState.AddModelError("", "Produto não existe");
                    return View(promocao);
				}

                var prom = db.Promocoes.Where(p => p.IdProduto == produto.IdProduto && p.Ativa == true).FirstOrDefault();
                if (prom != null)
                {
                    prom.Ativa = false;
                }
                db.Entry(promocao).State = EntityState.Modified;

                promocao.Ativa = true;
                promocao.PrecoNovo = produto.Preco - (produto.Preco * (promocao.Percentagem / (decimal)100));
                db.Promocoes.Add(promocao);

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
		}

        public ActionResult RemoverPromocao(int? id)
		{
            if (id != null)
			{
                return View(db.Promocoes.Find(id));
			}
            return RedirectToAction("Index");
		}

        [HttpPost]
        public ActionResult RemoverPromocao(int id)
		{
            var promocao = db.Promocoes.Find(id);
            if (promocao != null)
			{
                promocao.Ativa = false;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
		}

        // GET: Produtoes/Details/5
        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto prod = db.Produtos.Find(id);
            if (prod == null)
            {
                return HttpNotFound();
            }

            var produto = new ProdutoViewModel {
                NomeProduto = prod.Nome,
                IdProduto = prod.IdProduto,
                Categoria = prod.Categoria.NomeCategoria,
                Vendedor = prod.Empresa.NomeEmpresa,
                EmStock = prod.EmStock,
                Unidades = prod.UnidadesEmStock,
                Preco = prod.Preco,
                Apagado = prod.Apagado
            };

            var promocao = db.Promocoes.Where(p => p.IdProduto == prod.IdProduto && p.Ativa == true).FirstOrDefault();
            if (promocao != null)
            {
                produto.PrecoPromocional = promocao.PrecoNovo;
                produto.Desconto = promocao.Percentagem;
            }

            return View(produto);
        }


        // GET: Produtoes/Create
        [Authorize(Roles = "Empresa")]
        public ActionResult Create()
        {
            CriarProdutoViewModel model = new CriarProdutoViewModel();
            model.Categorias = new SelectList(db.Categorias, "IdCategoria", "NomeCategoria");
            return View(model);
        }

        // POST: Produtoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CriarProdutoViewModel model)
        {
            if (ModelState.IsValid)
            {
                var produto = new Produto
                {
                    Preco = model.Preco, UnidadesEmStock = model.UnidadesEmStock,
                    IdCategoria = model.IdCategoria, Nome = model.Nome
                };
                var userId = User.Identity.GetUserId();
                produto.IdEmpresa = db.Empresas.Where(e => e.ApplicationUserId == userId).FirstOrDefault().IdEmpresa;
                
                if (produto.UnidadesEmStock == 0)
				{
                    produto.EmStock = false;
				}
                else
				{
                    produto.EmStock = true;
				}

                db.Produtos.Add(produto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else{
                model.Categorias = new SelectList(db.Categorias, "IdCategoria", "NomeCategoria");
                return View(model);
            }   
        }

        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = db.Produtos.Find(id);

            if (produto == null)
            {
                return HttpNotFound();
            }

            return View(produto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "IdProduto,Nome,Preco,IdEmpresa,UnidadesEmStock,EmStock,IdCategoria")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                var promocao = db.Promocoes.Where(p => p.IdProduto == produto.IdProduto && p.Ativa == true).FirstOrDefault();
                if (promocao != null)
                {
                    promocao.Ativa = false;
                    db.Entry(promocao).State = EntityState.Modified;
                }

                db.Entry(produto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(produto);
        }

        // GET: Produtoes/Delete/5
        public ActionResult Apagar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

Views/Produtoes/Apagar.cshtml
@model TP_PWEB.Models.Produto

@{
    ViewBag.Title = "Delete";
}
<br />
<h5>Tem certeza que quer apagar este produto?</h5>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Empresa.NomeEmpresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empresa.NomeEmpresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Apagar" class="btn btn-danger" /> &nbsp;
            @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

Views/Produtoes/Create.cshtml
@model TP_PWEB.Models.CriarProdutoViewModel

@{ ViewBag.Title = "Registar Novo Produto"; }
<br />
<h5>Novo Produto</h5>

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*Desativa e ativa a validação no lado do cliente mas é sempre validada pelo servidor!! (Para corrigir erro decimal asp net)*@
                @{ Html.EnableClientValidation(false); }
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @{ Html.EnableClientValidation(true); }
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.UnidadesEmStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnidadesEmStock, new { htmlAttributes = new { @class = "form-control", @min = 0 } })
                @Html.ValidationMessageFor(model => model.UnidadesEmStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdCategoria, "Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.IdCategoria, Model.Categorias, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCategoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-success" />
            </div>
        </div>
    </div>
    
    }
<div>
    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")	
}

Views/Produtoes/CriarPromocao.cshtml
@model TP_PWEB.Models.Promocao
@{
    ViewBag.Title = "CriarPromocao";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h5>Nova Promocao</h5>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <input name="IdProduto" value="@ViewBag.Produto.IdProduto" type="hidden"/>
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdProduto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input name="Produto" value="@ViewBag.Produto.Nome" class="form-control" readonly/>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Percentagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Percentagem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Percentagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar Promocao" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

Views/Produtoes/Delete.cshtml
@model TP_PWEB.Models.Produto

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Empresa.NomeEmpresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empresa.NomeEmpresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Produtoes/Detalhes.cshtml
@model TP_PWEB.Models.ProdutoViewModel
@{
	ViewBag.Title = "Produto: " + Model.NomeProduto;
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />

<h5>Detalhes Produto@{
	if (Model.Apagado)
	{
		<span class="text-danger"> (APAGADO) </span>
	}
}</h5>
<div>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.NomeProduto)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.NomeProduto)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Categoria)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Categoria)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Vendedor)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Vendedor)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Preco)
		</dt>

		@{
			if (Model.PrecoPromocional == null)
			{
				<dd>
					@Html.DisplayFor(model => model.Preco)
				</dd>

			}
			else
			{
				<dd>
					<del>@Html.DisplayFor(model => model.Preco)</del> @Html.DisplayFor(model => model.PrecoPromocional) (- @Html.DisplayFor(model => model.Desconto) %)
				</dd>

			}
		}


		<dt>
			@Html.DisplayNameFor(model => model.EmStock)
		</dt>

		<dd>
			@if (Model.EmStock)
			{
				<p style="color: green;">Sim</p>
			}
			else
			{
				<p style="color: red;">Não</p>
			}
		</dd>

		@if (Model.EmStock)
		{
			<dt>
				@Html.DisplayNameFor(model => model.Unidades)
			</dt>

			<dd>
				@Html.DisplayFor(model => model.Unidades)
			</dd>
		}
	</dl>
</div>
<p>
    @if (User.IsInRole("Empresa"))
    {
        @Html.ActionLink("Editar", "Editar", new { id = Model.IdProduto }, new { @class = "btn btn-primary" }) @:&nbsp;
    }

    @if (User.IsInRole("Cliente") && Model.EmStock)
    {
        @Html.ActionLink(
            linkText: "Adicionar ao carrinho",
            actionName: "AdicionarItem",
            controllerName: "Carrinho",
            routeValues: new
            {
                id = Model.IdProduto
            },
            htmlAttributes: new
                    {
                @class = "btn btn-primary"
            })
        @:&nbsp;
    }

    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
</p>

Views/Produtoes/Edit.cshtml
@model TP_PWEB.Models.Produto

@{
    ViewBag.Title = "Editar Produto";
}
<h2>@Model.Nome</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Editar detalhes do produto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdProduto)
        @Html.HiddenFor(model => model.IdEmpresa)
        @Html.HiddenFor(model => model.IdCategoria)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnidadesEmStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnidadesEmStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnidadesEmStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EmStock)
                    @Html.ValidationMessageFor(model => model.EmStock, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Produtoes/Editar.cshtml
@model TP_PWEB.Models.Produto

@{
    ViewBag.Title = "Editar Produto";
}
<h2>@Model.Nome</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Editar detalhes do produto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdProduto)
        @Html.HiddenFor(model => model.IdEmpresa)
        @Html.HiddenFor(model => model.IdCategoria)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*Desativa e ativa a validação no lado do cliente mas é sempre validada pelo servidor!! (Para corrigir erro decimal asp net)*@
                @{ Html.EnableClientValidation(false); }
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @{ Html.EnableClientValidation(true); }
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnidadesEmStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnidadesEmStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnidadesEmStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EmStock)
                    @Html.ValidationMessageFor(model => model.EmStock, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Produtoes/Index.cshtml
@model IEnumerable<TP_PWEB.Models.ProdutoViewModel>

@{
    ViewBag.Title = "Catálogo de Produtos";
}
<br />
<br />
@if (User.IsInRole("Empresa"))
{
    <p>
        @Html.ActionLink("Novo Produto", "Create", null, new { @class = "btn btn-primary" })
    </p>
}
else if (User.IsInRole("Cliente"))
{

    using (Html.BeginForm("Index", "Produtoes", FormMethod.Get))
    {
        <div class="form-group row">
            <label class="col-sm-1 col-form-label">Produto</label>
            <div class="col-sm-10">
                <input name="produto" value="@ViewBag.Produto" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label">Categoria</label>
            <div class="col-sm-10">
                @Html.DropDownList("IdCategoria", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-10">
                <input type="submit" value="Pesquisar" class="btn btn-primary" />
            </div>
        </div>
    }
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NomeProduto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vendedor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmStock)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Unidades)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="10">De momento não existem produtos no catálogo.</td>
        </tr>
    }
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomeProduto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vendedor)
            </td>
            <td>
                @if (item.EmStock)
                {
                    <p style="color: green;">Sim</p>
                }
                else
                {
                    <p style="color: red;">Não</p>
                }
            </td>
            <td>
                x @Html.DisplayFor(modelItem => item.Unidades)
            </td>
            
            <td>
                @{
                    if (item.PrecoPromocional != null)
                    {

                        @:<del>@Html.DisplayFor(modelItem => item.Preco) </del> @Html.DisplayFor(modelItem => item.PrecoPromocional) (-@Html.DisplayFor(modelItem => item.Desconto) %)


                    }
                    else
                    {

                        @Html.DisplayFor(modelItem => item.Preco)

                    }
                }
            </td>

            <td>
                @Html.ActionLink("Detalhes", "Detalhes", new { id = item.IdProduto }, new { @class = "btn btn-info" }) &nbsp;

                @if (User.IsInRole("Cliente") && item.EmStock)
                {
                    @Html.ActionLink(
                        linkText: "Adicionar ao carrinho",
                        actionName: "AdicionarItem",
                        controllerName: "Carrinho",
                        routeValues: new
                        {
                            id = item.IdProduto
                        },
                        htmlAttributes: new
                                {
                            @class = "btn btn-primary"
                        }) @:&nbsp;
                }

                @if (User.IsInRole("Funcionario"))
                {
                    if (item.PrecoPromocional != null)
                    {
                        @Html.ActionLink("Remover Promoção", "RemoverPromocao", new { id = item.IdPromocao }, new { @class = "btn btn-warning" })
                    }
                    else
                    {
                        @Html.ActionLink("Criar Promoção", "CriarPromocao", new { id = item.IdProduto }, new { @class = "btn btn-primary" })
                    } @:&nbsp;
                }

                @if (User.IsInRole("Empresa"))
                {
                    if (item.Apagado)
                    {
                        <span class="label-danger">Produto Apagado</span>
                    }
                    else
                    {
                       
                        @Html.ActionLink("Editar", "Editar", new { id = item.IdProduto }, new { @class = "btn btn-warning" }) @:&nbsp;
                        @Html.ActionLink("Apagar", "Apagar", new { id = item.IdProduto }, new { @class = "btn btn-danger" })
                    }

                }
            </td>
            <td></td>
            <td></td>
        </tr>
    }
</table>

Views/Produtoes/RemoverPromocao.cshtml
@model TP_PWEB.Models.Promocao

@{
    ViewBag.Title = "RemoverPromocao";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h5>Tem a certeza que pretende remover a promoção do produto?</h5>
<div>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
    <br />
        <div class="form-actions no-color">
            <input type="submit" value="Remover" class="btn btn-warning" /> &nbsp;
            @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>